1 frontend code refactoring
Kv-126-DevOps/frontend pull request #2
Opened 2022-05-05 05:07 UTC by ViktorIshchenko

[frontend] Code refactoring

2022-05-09 12:29 UTC, anatolek requested changes

2022-05-09 12:29 UTC, anatolek commented on .env.example
> +POSTGRES_HOST=some_postgres_host
Not sure that this file is needed, so I guess it is better just add this info to the README.md and then remove this file at all

2022-05-09 12:29 UTC, anatolek commented on Dockerfile
> +COPY app app
You can use `--chown` option with COPY if you wish, see https://docs.docker.com/engine/reference/builder/#copy

2022-05-09 12:29 UTC, anatolek commented on README.md
> +### Setuping and Starting microservice
```suggestion
### Setting up and running a microservice
```

2022-05-09 12:29 UTC, anatolek commented on app/routes.py
> +PORT = os.environ.get('RESTAPI_PORT')
```suggestion
PORT = os.environ.get('RESTAPI_PORT', 5000)
```

2022-05-12 19:31 UTC, ViktorIshchenko commented on .env.example
> +POSTGRES_HOST=some_postgres_host
Deleted

2022-05-12 19:34 UTC, ViktorIshchenko commented on README.md
> +### Setuping and Starting microservice
OK

2022-05-12 19:36 UTC, ViktorIshchenko commented on app/routes.py
> +PORT = os.environ.get('RESTAPI_PORT')
+

2022-05-12 19:40 UTC, ViktorIshchenko commented
port added
.env.examples deleted
readme.md changed

2022-05-12 19:51 UTC, ViktorIshchenko commented on Dockerfile
> +COPY app app
fixed

2022-05-12 19:52 UTC, ViktorIshchenko commented
--chown=kvuser:kvuser

2022-05-14 11:20 UTC, anatolek approved these changes

2022-05-14 11:22 UTC, merged